### PR TITLE
Add support for --settings flag.

### PR DESCRIPTION
**Pull request by coopermaruyama**
- Add field to settings panel to specify path to settings.json file.
- Requires absolute path.
- Ensures the file exists before launching.

### CODE REVIEW

**Comment by PEM--** [comment]
Sounds pretty nice. Quick question, why did you force for an absolute path?

**Comment by coopermaruyama** [comment]
For some reason, when using a relative path it couldn't find the settings.json file. assuming that the 'starting directory' is the app's root, it should work as is with a relative directory, but for some reason it didn't work for me. Maybe you can shed some light on this and I can update it?

**Comment by coopermaruyama** [comment]
Nevermind, I wasn't aware of `atom.project.getPath()`, pushing new release now which supports both relative and absolute.

**Comment by coopermaruyama** [comment]
Done. It now uses absolute if 1st character is `/`, otherwise uses relative starting at project directory.

**Comment by PEM--** [comment]
Awesome :star:

**Comment by PEM--** [comment]
And published as the 0.25.0. Thanks :clap:

**Pull request merged**
